Skip checks that haven't been configured
Previously if a check class existed but you haven't added any
configuration for it in the config YAML, then you'd get a non-obvious
exception (NoMethodError: undefined method `dig' for nil:NilClass).

This commit changes the behaviour so that check that have no
configuration are just skipped.

Fixes #17